### ISSUE TITLE
Certain pattern string not accepted for RgxGen

### ISSUE THREAD

**Issue by code-lucidal58** [curious-odd-man/RgxGen#53]
**Describe the bug**
New RgxGen object creation fails with StringIndexOutOfBoundsException, when passing the pattern string `^[a-zA-Z0-9-._:]*$`.

**To Reproduce**
Creating a new RgxGen with the pattern string `^[a-zA-Z0-9-._:]*$`.
```RgxGen rgxGen = new RgxGen(pattern);```

**Expected behavior**
Successfully create the object

**Error Log**
```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:237)
	at java.lang.StringBuilder.charAt(StringBuilder.java:76)
	at com.github.curiousoddman.rgxgen.parsing.dflt.DefaultTreeBuilder.handleRange(DefaultTreeBuilder.java:417)
	at com.github.curiousoddman.rgxgen.parsing.dflt.DefaultTreeBuilder.handleCharacterVariations(DefaultTreeBuilder.java:505)
	at com.github.curiousoddman.rgxgen.parsing.dflt.DefaultTreeBuilder.parseGroup(DefaultTreeBuilder.java:149)
	at com.github.curiousoddman.rgxgen.parsing.dflt.DefaultTreeBuilder.build(DefaultTreeBuilder.java:521)
	at com.github.curiousoddman.rgxgen.parsing.dflt.DefaultTreeBuilder.get(DefaultTreeBuilder.java:530)
	at com.github.curiousoddman.rgxgen.RgxGen.<init>(RgxGen.java:52)
	at com.github.curiousoddman.rgxgen.RgxGen.<init>(RgxGen.java:43)
```

**Environment (please complete the following information):**
 - OS: MacOS
 - JDK/JRE version 
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.275-b01, mixed mode)
 - RgxGen Version or commit id
Code at tag 1.2 https://github.com/curious-odd-man/RgxGen/blob/1.2/src/main/java/com/github/curiousoddman/rgxgen/parsing/dflt/DefaultTreeBuilder.java

**Comment by curious-odd-man** [comment]
Dear @code-lucidal58. The issue have been resolved in a version 1.3-SNAPSHOT.

You can use this version as explained in [README](https://github.com/curious-odd-man/RgxGen#the-latest-snapshot) or wait for version 1.3 release.

Please let me know if there are any other issues.

**Comment by spacether** [comment]
@curious-odd-man would it be possible for you to publish a non snapshot version before Dec 16th?
In openapi-generator we want to include this fix and we are doing a major rev roll but we don't wannt to install a snapshot version. See https://github.com/OpenAPITools/openapi-generator/pull/8139#discussion_r539362589

**Comment by curious-odd-man** [comment]
@spacether sure. I'll do my best. I'll drop a comment in referenced issue once release is done.

**Comment by spacether** [comment]
Thank you! I completely understand if you are too busy also.
